export const investors = [
  {
      id: 1,
      name: "Morgan Freeman",
      initAvatar: { title: "M", variant: "soft-warning" },
      email: "morgan@jampack.com",
      phone: "+145 52 5689",
      category: "Inventory",
  },
  {
      id: 2,
      name: "Huma Therman",
      initAvatar: { title: "H", variant: "soft-primary" },
      email: "huma@clariesup.au",
      phone: "+234 48 2365",
      category: "PPF",
  },
  {
      id: 3,
      name: "Charlie Chaplin",
      initAvatar: { title: "C", variant: "soft-info" },
      email: "charlie@jampack.com",
      phone: "+145 52 5689",
      category: "Real Estate",
  },
  {
      id: 4,
      name: "Winston Churchil",
      initAvatar: { title: "W", variant: "soft-primary" },
      email: "winston@jampack.com",
      phone: "+234 48 2365",
      category: "Fixed Deposits",
  },
  {
      id: 5,
      name: "Clive Lloyd",
      initAvatar: { title: "C", variant: "soft-danger" },
      email: "clive@rediff.com",
      phone: "+145 52 5689",
      category: "Real Estate",
  },
  {
      id: 6,
      name: "Steve Yordley",
      initAvatar: { title: "S", variant: "soft-primary" },
      email: "steve@yahoo.com",
      phone: "+234 48 2365",
      category: "Fixed Deposits",
  },
  {
      id: 7,
      name: "Hencework",
      initAvatar: { title: "H", variant: "soft-danger" },
      email: "hencework@gmail.com",
      phone: "+145 52 5689",
      category: "PPF",
  },
  {
      id: 8,
      name: "Jaquiline Joker",
      initAvatar: { title: "J", variant: "soft-primary" },
      email: "joker@rediff.com",
      phone: "+234 48 2365",
      category: "Real Estate",
  },
  {
      id: 9,
      name: "Tom Cruz",
      initAvatar: { title: "T", variant: "soft-warning" },
      email: "tom@jampack.com",
      phone: "+145 52 5689",
      category: "PPF",
  },
  {
      id: 10,
      name: "Katherine Jones",
      initAvatar: { title: "K", variant: "soft-primary" },
      email: "jones@jampack.com",
      phone: "+234 48 2365",
      category: "Fixed Deposits",
  },
]